var mainContainer_photo = document.querySelector('.restaurant');
var img1 = document.createElement('img');
img1.classList.add('img1');
img1.src = "photo_5217566704459171374_x 1.png";
mainContainer_photo.appendChild(img1);

var img2 = document.createElement('img');
img2.classList.add('img2');
img2.src = "IMG_20230507_093602.jpg";
mainContainer_photo.appendChild(img2);

var img3 = document.createElement('img');
img3.classList.add('img3');
img3.src = "photo_5248976148187170913_y.jpg";
mainContainer_photo.appendChild(img3);

var img4 = document.createElement('img');
img4.classList.add('img4');
img4.src = "IMG_20230507_093519.jpg";
mainContainer_photo.appendChild(img4);


//головний контейнер
var mainContainer_menu = document.querySelector('.lines');
//контейнер в контейнері
var container = document.createElement('div');
container.classList.add('cart');

var img = document.createElement('img');
img.classList.add('croissants');
img.src = "Amsterdam.png" ;
container.appendChild(img);

//контейнер з текстовою інфою
var container_text = document.createElement('div');
 container_text.classList.add('content');
//його вміст
var t = document.createElement('div');
t.classList.add('food');
t.textContent = "Королівський круасан";
container_text.appendChild(t);


var component = document.createElement('div');
component.classList.add('component');
component.textContent = "круасан, огірок, помідор, салямі, сир тостовий, яєчня, салат, соус часниковий";
container_text.appendChild(component);

var price = document.createElement('div');
price.classList.add('price');
price.textContent = "79 грн";
container_text.appendChild(price);

var img_2 = document.createElement('img');
img_2.classList.add('strip');
img_2.src = "Line 57.svg";
container_text.appendChild(img_2);

container.appendChild(container_text);
mainContainer_menu.append(container);

//головний контейнер 2 блок
var mainContainer_menu = document.querySelector('.lines');
//контейнер в контейнері
var container = document.createElement('div');
container.classList.add('cart');

var img = document.createElement('img');
img.classList.add('croissants');
img.src = "Amsterdam.png" ;
container.appendChild(img);

//контейнер з текстовою інфою
var container_text = document.createElement('div');
 container_text.classList.add('content');
//його вміст
var t = document.createElement('div');
t.classList.add('food');
t.textContent = "Королівський круасан";
container_text.appendChild(t);


var component = document.createElement('div');
component.classList.add('component');
component.textContent = "круасан, огірок, помідор, салямі, сир тостовий, яєчня, салат, соус часниковий";
container_text.appendChild(component);

var price = document.createElement('div');
price.classList.add('price');
price.textContent = "79 грн";
container_text.appendChild(price);

var img_2 = document.createElement('img');
img_2.classList.add('strip');
img_2.src = "Line 57.svg";
container_text.appendChild(img_2);

container.appendChild(container_text);
mainContainer_menu.append(container);


//головний контейнер 3 блок
var mainContainer_menu = document.querySelector('.lines');
//контейнер в контейнері
var container = document.createElement('div');
container.classList.add('cart');

var img = document.createElement('img');
img.classList.add('croissants');
img.src = "Amsterdam.png" ;
container.appendChild(img);

//контейнер з текстовою інфою
var container_text = document.createElement('div');
 container_text.classList.add('content');
//його вміст
var t = document.createElement('div');
t.classList.add('food');
t.textContent = "Королівський круасан";
container_text.appendChild(t);


var component = document.createElement('div');
component.classList.add('component');
component.textContent = "круасан, огірок, помідор, салямі, сир тостовий, яєчня, салат, соус часниковий";
container_text.appendChild(component);

var price = document.createElement('div');
price.classList.add('price');
price.textContent = "79 грн";
container_text.appendChild(price);

var img_2 = document.createElement('img');
img_2.classList.add('strip');
img_2.src = "Line 57.svg";
container_text.appendChild(img_2);

container.appendChild(container_text);
mainContainer_menu.append(container);



//головний контейнер 4 блок
var mainContainer_menu = document.querySelector('.lines');
//контейнер в контейнері
var container = document.createElement('div');
container.classList.add('cart');

var img = document.createElement('img');
img.classList.add('croissants');
img.src = "Amsterdam.png" ;
container.appendChild(img);

//контейнер з текстовою інфою
var container_text = document.createElement('div');
 container_text.classList.add('content');
//його вміст
var t = document.createElement('div');
t.classList.add('food');
t.textContent = "Королівський круасан";
container_text.appendChild(t);


var component = document.createElement('div');
component.classList.add('component');
component.textContent = "круасан, огірок, помідор, салямі, сир тостовий, яєчня, салат, соус часниковий";
container_text.appendChild(component);

var price = document.createElement('div');
price.classList.add('price');
price.textContent = "79 грн";
container_text.appendChild(price);

var img_2 = document.createElement('img');
img_2.classList.add('strip');
img_2.src = "Line 57.svg";
container_text.appendChild(img_2);

container.appendChild(container_text);
mainContainer_menu.append(container);



//головний контейнер 5 блок
var mainContainer_menu = document.querySelector('.lines');
//контейнер в контейнері
var container = document.createElement('div');
container.classList.add('cart');

var img = document.createElement('img');
img.classList.add('croissants');
img.src = "Amsterdam.png" ;
container.appendChild(img);

//контейнер з текстовою інфою
var container_text = document.createElement('div');
 container_text.classList.add('content');
//його вміст
var t = document.createElement('div');
t.classList.add('food');
t.textContent = "Королівський круасан";
container_text.appendChild(t);


var component = document.createElement('div');
component.classList.add('component');
component.textContent = "круасан, огірок, помідор, салямі, сир тостовий, яєчня, салат, соус часниковий";
container_text.appendChild(component);

var price = document.createElement('div');
price.classList.add('price');
price.textContent = "79 грн";
container_text.appendChild(price);

var img_2 = document.createElement('img');
img_2.classList.add('strip');
img_2.src = "Line 57.svg";
container_text.appendChild(img_2);

container.appendChild(container_text);
mainContainer_menu.append(container);



//головний контейнер 6 блок
var mainContainer_menu = document.querySelector('.lines');
//контейнер в контейнері
var container = document.createElement('div');
container.classList.add('cart');

var img = document.createElement('img');
img.classList.add('croissants');
img.src = "Amsterdam.png" ;
container.appendChild(img);

//контейнер з текстовою інфою
var container_text = document.createElement('div');
 container_text.classList.add('content');
//його вміст
var t = document.createElement('div');
t.classList.add('food');
t.textContent = "Королівський круасан";
container_text.appendChild(t);


var component = document.createElement('div');
component.classList.add('component');
component.textContent = "круасан, огірок, помідор, салямі, сир тостовий, яєчня, салат, соус часниковий";
container_text.appendChild(component);

var price = document.createElement('div');
price.classList.add('price');
price.textContent = "79 грн";
container_text.appendChild(price);

var img_2 = document.createElement('img');
img_2.classList.add('strip');
img_2.src = "Line 57.svg";
container_text.appendChild(img_2);

container.appendChild(container_text);
mainContainer_menu.append(container);
